export type ParameterMapping={name:string;value:string;mappingName?:string};
export type EvalPlatform={id:string;name:string;description:string;dimensions:string[];provider:string;email:string;phone?:string;enabled:boolean;connected:'success'|'failed'|'untested';url?:string;timeout?:number;requestMethod?:'GET'|'POST';queryParameters?:ParameterMapping[];responseParameters?:ParameterMapping[];deployment:string;pythonVersion:string;deploymentStatus:string;image?:string;servicePort?:string;taskPort?:string;repository?:string;evaluationMethod:string;modelName?:string;baseUrl?:string;apiKey?:string;script?:string;documentName?:string;draft?:boolean;updatedAt:string;preset?:boolean};

export const presetPlatforms:EvalPlatform[]=[
 {id:'medbench',name:'medbench',description:'上海AI实验室（浦江实验室）联合瑞金医院出品；基于OpenCompass（司南）的中文医疗大模型开放评测平台',dimensions:['临床任务规划与推理','医疗工具调用与执行','医疗场景感知与交互','记忆与上下文保持','医疗多智能体协作'],provider:'浦江实验室',email:'medbench@pjlab.org.cn',enabled:false,connected:'untested',deployment:'无需部署',pythonVersion:'无要求',deploymentStatus:'无需部署',evaluationMethod:'内置评估器',updatedAt:'2026-08-12 09:30:00',preset:true},
 {id:'cp-env',name:'CP-Env',description:'模拟完整临床诊疗流程，同时模拟病人AI和医生AI进行交互式诊疗过程，评估临床效果、流程能力与职业医德',dimensions:['Clinical Efficacy','Process Competency','Professional Ethics'],provider:'上海交通大学&香港中文大学',email:'xiaofan.zhang@sjtu.edu.cn',enabled:false,connected:'untested',deployment:'pip安装',pythonVersion:'其他',deploymentStatus:'未部署',repository:'https://github.com/SPIRAL-MED/CP_ENV',evaluationMethod:'裁判大模型',modelName:'',baseUrl:'',apiKey:'',updatedAt:'2026-08-12 09:20:00',preset:true},
 {id:'medagentbench',name:'MedAgentbench',description:'斯坦福大学团队发布，通过本地部署的FHIR标准电子病历服务器与智能体实时交互，评测300个临床任务',dimensions:['Patient information retrieval','Lab result retrieval','Patient data aggregation','Recording patient data','Test ordering','Referral ordering','Medication ordering'],provider:'斯坦福大学',email:'',enabled:false,connected:'untested',deployment:'Docker容器',pythonVersion:'3.9',deploymentStatus:'未部署',image:'jyxsu6/medagentbench:latest',servicePort:'8080',taskPort:'5000-5015',repository:'https://github.com/stanfordmlgroup/MedAgentBench',evaluationMethod:'python脚本',script:'python -m src.client.agent_test --config configs/agents/api_agents.yaml --agent gpt-4o-mini\npython -m src.start_task -a\npython -m src.assigner',updatedAt:'2026-08-12 09:10:00',preset:true},
];
const KEY='evaluation-platforms-v1';
export const loadPlatforms=():EvalPlatform[]=>{try{const x=localStorage.getItem(KEY);return x?JSON.parse(x):presetPlatforms}catch{return presetPlatforms}};
export const savePlatforms=(rows:EvalPlatform[])=>localStorage.setItem(KEY,JSON.stringify(rows));
export const now=()=>new Date().toLocaleString('sv-SE').replace('T',' ');
